@ECHO OFF

#Server Port
set SERVER_PORT=8081

#JHipster Registry
set JHIPSTER_REGISTRY_SERVER_IP=192.168.25.128
set JHIPSTER_REGISTRY_SERVER_PORT=8761

#MongoDB
set MONGODB_SERVER_IP=192.168.25.128
set MONGODB_SERVER_PORT=27017
set MONGODB_SERVER_DB=backendapi

set PATH=%PATH%;%JHIPSTER_REGISTRY_SERVER_IP$;%JHIPSTER_REGISTRY_SERVER_PORT%;%MONGODB_SERVER_IP%;%MONGODB_SERVER_PORT%;%MONGODB_SERVER_DB%;